### ISSUE TITLE
Some features requests

### ISSUE THREAD

**Issue by ycopin** [dcmvdbekerom/pypdfplot#17]
I have few usability questions:
* I wonder if it would be interesting to have a finer control of the I/O with *additional* possibilities, e.g.:
  * `python -m pypdfplot embed myscript.py -o myplot.pdf` would generate the PDF plot and embed the script
  * `python -m pypdfplot extract myplot.pdf -o myscript.py` would extract embedded script from PDF plot
* Is there any possibility to do such a trick with PNG files? (or other bitmap formats)

Thanks again for the package!

**Comment by dcmvdbekerom** [comment]
The problem I see with the ``embed`` function is that it would be possible to embed a python script ``myscript.py`` that _does not_ generate the pdf ``myplot.pdf``, this would be against the philosophy of ``pypdfplot``. To ensure that the embedded script and the pdf-plot are the same, you could just run ``python myscript.py``. What finer control would you gain from ``python -m pypdfplot embed myscript.py -o myplot.pdf``? Please feel free to correct me if I didn't get the functionality your suggesting right.

The ``extract`` option would make more sense I suppose, but would this really be more convenient than opening the file in a text editor?

As for PNG or other bitmaps, the answer is unfortunately almost certainly no. The reason it works with PDF is that PDF files can be stored completely as ASCII text, which can be read by a Python interpreter. Bitmaps store their data as bytes, which can confuse the Python interpreter. Moreover, the PDF specification is quite lenient in adding additional blocks of data that don't have anything to do with the document (although the extra 'garbage' is quite minimal for pypdfplot!), this is also not usually the case in other file formats, particularly in the file header where we would like to put our Python code. 

Conversely, it's quite easy to combine PDF with other languages than Python, LaTeX being a prime example. It would be relatively easy to make a package that would compile LaTeX files and embed them in a PDF, but I don't think this would be as useful as in the case of Python + PDF.

EDIT:
You can run ``publish()`` with the keyword ``cleanup = False`` to extract the Python script (and other embedded files).

**Comment by dcmvdbekerom** [comment]
After thinking about it a bit more I think finer control via command line can be made to work and would indeed be a good idea.

Let's move discussion to a separate issue here https://github.com/dcmvdbekerom/pypdfplot/issues/39
